import { useEffect, useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Music2, Plus, Trash2, Upload, X } from "lucide-react";
import { deleteCreatorPostAdmin, getCreatorPostsAdmin, saveCreatorPostAdmin } from "@/lib/creator-posts.functions";
import { abortR2MultipartMediaUpload, completeR2MultipartMediaUpload, confirmR2MediaUpload, prepareR2MediaUpload, prepareR2MultipartPartUpload } from "@/lib/media-storage.functions";
import { uploadFileToR2 } from "@/lib/r2-upload";
import { ProfileAudioPlayer } from "@/components/ProfileAudioPlayer";

type MediaItem={mediaKey:string;mediaType:"image"|"video";mediaUrl:string};
type UploadProgress={total:number;completed:number;currentPercent:number;currentName:string;status:"uploading"|"success"|"error"};
const newForm=()=>({id:"",caption:"",mediaItems:[] as MediaItem[],audioKey:"",audioTitle:"",audioUrl:"",publishedAt:new Date().toISOString().slice(0,16),isActive:true,likes:0,fire:0,heartEyes:0,laugh:0,clap:0});

export function ModelPostsManager({model}:{model:{id:string;name:string;username:string;profile_image_path:string|null}}){
  const load=useServerFn(getCreatorPostsAdmin),save=useServerFn(saveCreatorPostAdmin),remove=useServerFn(deleteCreatorPostAdmin),prepare=useServerFn(prepareR2MediaUpload),confirm=useServerFn(confirmR2MediaUpload),part=useServerFn(prepareR2MultipartPartUpload),complete=useServerFn(completeR2MultipartMediaUpload),abort=useServerFn(abortR2MultipartMediaUpload);
  const[data,setData]=useState<any>({posts:[],gifts:[]}),[form,setForm]=useState<any>(newForm()),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[uploadProgress,setUploadProgress]=useState<UploadProgress|null>(null),[isDraggingMedia,setIsDraggingMedia]=useState(false);
  async function refresh(){setBusy(true);try{setData(await load({data:{creatorId:model.id}}));setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{setBusy(false)}}
  useEffect(()=>{void refresh()},[model.id]);
  async function uploadFiles(files:File[],kind:"media"|"audio"){
    if(!files.length)return;if(kind==="media"&&form.mediaItems.length+files.length>10){setError("Cada post pode ter no máximo 10 fotos ou vídeos.");return}setBusy(true);setError("");setUploadProgress({total:files.length,completed:0,currentPercent:0,currentName:files[0].name,status:"uploading"});
    try{const uploaded:MediaItem[]=[];for(const [fileIndex,file] of files.entries()){setUploadProgress({total:files.length,completed:fileIndex,currentPercent:0,currentName:file.name,status:"uploading"});const p=await prepare({data:{modelId:model.id,scope:"content",filename:file.name,contentType:file.type,size:file.size}});if(kind==="audio"&&p.mediaType!=="audio")throw new Error("Selecione um arquivo de áudio válido.");if(kind==="media"&&p.mediaType==="audio")throw new Error("O carrossel aceita apenas imagens e vídeos.");await uploadFileToR2({prepared:p,file,contentType:file.type,onProgress:currentPercent=>setUploadProgress({total:files.length,completed:fileIndex,currentPercent,currentName:file.name,status:"uploading"}),getPartUrl:d=>part({data:d}),completeMultipart:d=>complete({data:d}),abortMultipart:d=>abort({data:d})});await confirm({data:{modelId:model.id,scope:"content",reference:p.reference}});setUploadProgress({total:files.length,completed:fileIndex+1,currentPercent:0,currentName:file.name,status:"uploading"});if(kind==="audio")setForm((current:any)=>({...current,audioKey:p.reference,audioUrl:URL.createObjectURL(file)}));else uploaded.push({mediaKey:p.reference,mediaType:p.mediaType as "image"|"video",mediaUrl:URL.createObjectURL(file)})}if(uploaded.length)setForm((current:any)=>({...current,mediaItems:[...current.mediaItems,...uploaded]}));setUploadProgress({total:files.length,completed:files.length,currentPercent:100,currentName:"Upload concluído",status:"success"});window.setTimeout(()=>setUploadProgress(current=>current?.status==="success"?null:current),3500)}catch(e){setError(e instanceof Error?e.message:"Falha no upload.");setUploadProgress(current=>current?{...current,status:"error"}:null)}finally{setBusy(false)}
  }
  function receiveMediaFiles(files:File[]){
    if(busy||!files.length)return;
    const supported=files.filter(file=>file.type.startsWith("image/")||file.type==="video/mp4"||file.type==="video/webm");
    if(supported.length!==files.length){setError("Arraste apenas imagens ou vídeos MP4 e WEBM.");return}
    void uploadFiles(supported,"media");
  }
  async function submit(){setBusy(true);setError("");try{await save({data:{...form,creatorId:model.id}});setEditing(false);setForm(newForm());await refresh()}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.")}finally{setBusy(false)}}
  function edit(p:any){setForm({id:p.id,caption:p.caption,mediaItems:(p.media??[]).map((m:any)=>({mediaKey:m.media_key,mediaType:m.media_type,mediaUrl:m.media_url})),audioKey:p.audio_key??"",audioTitle:p.audio_title??"",audioUrl:p.audio_url??"",publishedAt:new Date(p.published_at).toISOString().slice(0,16),isActive:p.is_active,likes:p.likes_count,fire:p.fire_count,heartEyes:p.heart_eyes_count,laugh:p.laugh_count,clap:p.clap_count});setEditing(true)}
  const gifts=useMemo(()=>data.gifts.filter((g:any)=>filter==="all"||g.status===filter),[data.gifts,filter]);const paid=data.gifts.filter((g:any)=>g.status==="paid"),revenue=paid.reduce((sum:number,g:any)=>sum+Number(g.amount),0);
  return <div className="space-y-8">
    {uploadProgress?<UploadProgressToast progress={uploadProgress} onClose={()=>setUploadProgress(null)}/>:null}
    {error?<div role="alert" className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error}<button onClick={refresh} className="ml-3 font-bold">Tentar novamente</button></div>:null}
    <section><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-black">Posts</h3><p className="text-sm text-muted-foreground">Feed exclusivo da área paga.</p></div><button onClick={()=>{setForm(newForm());setEditing(true)}} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-bold text-white"><Plus className="h-4 w-4"/>Novo post</button></div>
      {editing?<div className="mt-5 grid gap-5 rounded-2xl border border-border p-4 sm:p-5 lg:grid-cols-2"><div className="space-y-4">
        <label className="block text-sm font-bold">Legenda<textarea value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})} rows={4} className="mt-2 w-full rounded-xl border p-3"/></label>
        <div>
          <p className="text-sm font-bold">Fotos e vídeos</p>
          <label
            className={`mt-2 flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border border-dashed px-4 py-5 text-center transition-[border-color,background-color,transform] duration-150 ${isDraggingMedia?"scale-[1.01] border-primary bg-primary/10 text-primary":"border-border bg-muted/15 hover:border-primary/60 hover:bg-primary/5"} ${busy?"pointer-events-none opacity-60":""}`}
            onDragEnter={event=>{event.preventDefault();if(!busy)setIsDraggingMedia(true)}}
            onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";if(!busy)setIsDraggingMedia(true)}}
            onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setIsDraggingMedia(false)}}
            onDrop={event=>{event.preventDefault();setIsDraggingMedia(false);receiveMediaFiles(Array.from(event.dataTransfer.files))}}
            aria-busy={busy}
          >
            <span className={`grid h-10 w-10 place-items-center rounded-xl ${isDraggingMedia?"bg-primary text-white":"bg-primary/10 text-primary"}`}>
              <Upload className="h-5 w-5"/>
            </span>
            <span className="text-sm font-bold">{isDraggingMedia?"Solte os arquivos aqui":"Arraste fotos e vídeos para cá"}</span>
            <span className="text-xs text-muted-foreground">ou clique para adicionar ao carrossel</span>
            <input multiple type="file" accept="image/*,video/mp4,video/webm" className="sr-only" onChange={event=>{receiveMediaFiles(Array.from(event.target.files??[]));event.target.value=""}}/>
          </label>
          <p className="mt-1 text-xs text-muted-foreground">Até 10 arquivos. A ordem de seleção será mantida.</p>
        </div>
        {form.mediaItems.length?<div className="grid grid-cols-4 gap-2">{form.mediaItems.map((item:MediaItem,index:number)=><div key={`${item.mediaKey}-${index}`} className="relative aspect-square overflow-hidden rounded-xl bg-black">{item.mediaType==="video"?<video src={item.mediaUrl} muted className="h-full w-full object-cover"/>:<img src={item.mediaUrl} alt="" className="h-full w-full object-cover"/>}<button type="button" onClick={()=>setForm({...form,mediaItems:form.mediaItems.filter((_:MediaItem,i:number)=>i!==index)})} aria-label={`Remover mídia ${index+1}`} className="absolute right-1 top-1 grid h-8 w-8 place-items-center rounded-full bg-black/70 text-white"><X className="h-4 w-4"/></button><span className="absolute bottom-1 left-1 rounded bg-black/65 px-1.5 text-xs font-bold text-white">{index+1}</span></div>)}</div>:null}
        <div className="rounded-2xl border border-border bg-muted/20 p-4"><div className="flex items-center gap-2"><Music2 className="h-4 w-4 text-primary"/><p className="text-sm font-bold">Áudio do post <span className="font-normal text-muted-foreground">(opcional)</span></p></div><input value={form.audioTitle} maxLength={80} onChange={e=>setForm({...form,audioTitle:e.target.value})} placeholder="Título do áudio" className="mt-3 min-h-11 w-full rounded-xl border px-3 text-sm"/><div className="mt-2 flex gap-2"><label className="inline-flex min-h-11 flex-1 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed px-3 text-sm font-bold"><Upload className="h-4 w-4"/>{form.audioKey?"Substituir áudio":"Enviar áudio"}<input type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.opus,.webm,.flac" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadFiles([file],"audio");e.target.value=""}}/></label>{form.audioKey?<button type="button" onClick={()=>setForm({...form,audioKey:"",audioUrl:"",audioTitle:""})} className="rounded-xl px-3 text-sm font-bold text-destructive">Remover</button>:null}</div></div>
        <label className="block text-sm font-bold">Publicação<input type="datetime-local" value={form.publishedAt} onChange={e=>setForm({...form,publishedAt:e.target.value})} className="mt-2 min-h-12 w-full rounded-xl border px-3"/></label><label className="flex gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Ativo</label>
        <div className="grid grid-cols-5 gap-2">{[["❤️","likes"],["🔥","fire"],["😍","heartEyes"],["😂","laugh"],["👏","clap"]].map(([label,key])=><label className="text-center text-sm" key={key}>{label}<input type="number" min="0" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div>
        <div className="flex gap-2"><button disabled={busy||!form.mediaItems.length} onClick={submit} className="min-h-11 flex-1 rounded-xl bg-primary font-bold text-white disabled:opacity-50">{busy?"Salvando…":"Salvar post"}</button><button onClick={()=>setEditing(false)} className="rounded-xl border px-4">Cancelar</button></div>
      </div><PostPreview form={form} model={model}/></div>:null}
      <div className="mt-5 space-y-3">{busy&&!data.posts.length?<p>Carregando posts…</p>:data.posts.length?data.posts.map((p:any)=><div key={p.id} className="flex items-center gap-4 rounded-xl border p-3"><img src={p.media_url} alt="" className="h-16 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-bold">{p.caption||"Sem legenda"}</p><p className="text-xs text-muted-foreground">{new Date(p.published_at).toLocaleString("pt-BR")} · {p.media?.length||1} mídia(s){p.audio_key?" · com áudio":""} · {p.is_active?"Ativo":"Inativo"}</p></div><button onClick={()=>edit(p)} className="min-h-11 px-3 font-bold">Editar</button><button aria-label="Excluir post" onClick={async()=>{await remove({data:{id:p.id,creatorId:model.id}});await refresh()}} className="grid h-11 w-11 place-items-center text-destructive"><Trash2 className="h-4 w-4"/></button></div>):<p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">Nenhuma postagem disponível ainda.</p>}</div>
    </section><GiftsSection gifts={gifts} paid={paid} revenue={revenue} filter={filter} setFilter={setFilter}/>
  </div>
}

function UploadProgressToast({progress,onClose}:{progress:UploadProgress;onClose:()=>void}){
  const overall=Math.round(((progress.completed+(progress.status==="uploading"?progress.currentPercent/100:0))/Math.max(1,progress.total))*100);
  const percent=progress.status==="success"?100:Math.min(100,overall);
  return <aside aria-live="polite" className="fixed inset-x-3 bottom-[max(1rem,env(safe-area-inset-bottom))] z-[150] mx-auto w-auto max-w-md rounded-2xl border border-border bg-white p-4 shadow-[0_18px_48px_rgba(35,25,20,.24)] sm:left-auto sm:right-5 sm:mx-0 sm:w-[390px]">
    <div className="flex items-start gap-3">
      <span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${progress.status==="error"?"bg-destructive/10 text-destructive":progress.status==="success"?"bg-emerald-50 text-emerald-600":"bg-primary/10 text-primary"}`}>{progress.status==="error"?<AlertCircle className="h-5 w-5"/>:progress.status==="success"?<CheckCircle2 className="h-5 w-5"/>:<Upload className="h-5 w-5"/>}</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="font-bold text-foreground">{progress.status==="error"?"Falha no upload":progress.status==="success"?"Upload concluído":"Enviando arquivos"}</p><span className="shrink-0 text-sm font-bold tabular-nums text-muted-foreground">{progress.completed}/{progress.total}</span></div><p className="mt-0.5 truncate text-xs text-muted-foreground">{progress.currentName}</p></div>
      {progress.status!=="uploading"?<button type="button" onClick={onClose} aria-label="Fechar progresso do upload" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-muted-foreground hover:bg-muted"><X className="h-4 w-4"/></button>:null}
    </div>
    <div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full transition-[width] duration-200 ${progress.status==="error"?"bg-destructive":"bg-primary"}`} style={{width:`${percent}%`}}/></div>
    <div className="mt-2 flex justify-between text-xs font-semibold text-muted-foreground"><span>{progress.status==="uploading"?`${percent}% enviado`:progress.status==="success"?"Todos os arquivos foram enviados":"Verifique sua conexão e tente novamente"}</span><span>{progress.total===1?"1 arquivo":`${progress.total} arquivos`}</span></div>
  </aside>
}

function GiftsSection({gifts,paid,revenue,filter,setFilter}:any){return <section><h3 className="text-lg font-black">Presentes recebidos</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Presentes pagos",paid.length],["Receita com presentes",revenue.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})],["Ticket médio",paid.length?(revenue/paid.length).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"R$ 0,00"]].map(([label,value])=><div className="rounded-xl border p-4" key={String(label)}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div><div className="my-4 flex gap-1">{[["all","Todos"],["pending","Pendentes"],["paid","Pagos"]].map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===value?"bg-primary text-white":"bg-muted"}`}>{label}</button>)}</div>{gifts.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Data","Cliente","Telefone","Valor","Mensagem","Post","Status","Transaction ID"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{gifts.map((g:any)=><tr key={g.id} className="border-t"><td className="p-3">{new Date(g.created_at).toLocaleString("pt-BR")}</td><td>{g.customers?.name}</td><td>{g.buyer_phone}</td><td>{Number(g.amount).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</td><td className="min-w-56 max-w-80 whitespace-pre-wrap py-3 pr-3 text-muted-foreground">{g.message||"—"}</td><td>{g.creator_posts?.caption?.slice(0,30)||"—"}</td><td>{g.status}</td><td className="max-w-40 truncate">{g.transaction_identifier||"—"}</td></tr>)}</tbody></table></div>:<p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">Essa criadora ainda não recebeu presentes.</p>}</section>}

function PostPreview({form,model}:{form:any;model:any}){const[index,setIndex]=useState(0);useEffect(()=>setIndex(0),[form.mediaItems.length]);const item=form.mediaItems[index];const reactions=[["❤️",form.likes],["🔥",form.fire],["😍",form.heartEyes],["😂",form.laugh],["👏",form.clap]].filter(([,count])=>Number(count)>0);return <div><p className="mb-3 text-sm font-bold">Prévia</p><article className="mx-auto max-w-[420px] overflow-hidden rounded-[1.25rem] border bg-white shadow-[0_10px_30px_rgba(45,33,27,.08)]"><header className="flex items-center gap-3 p-4"><div className="h-11 w-11 rounded-full bg-muted ring-2 ring-primary ring-offset-2"/><div className="min-w-0 flex-1"><p className="truncate font-bold">{model.name}</p><p className="truncate text-sm text-muted-foreground">@{model.username}</p></div></header><p className="px-4 pb-3 text-sm leading-relaxed">{form.caption||"Sua legenda aparecerá aqui."}</p>{form.audioUrl?<div className="mx-3 mb-3 overflow-hidden rounded-2xl border"><ProfileAudioPlayer title={form.audioTitle||"Ouça esta mensagem"} src={form.audioUrl}/></div>:null}{item?<div className="relative mx-3 aspect-[3/4] overflow-hidden rounded-2xl bg-black">{item.mediaType==="video"?<video src={item.mediaUrl} autoPlay muted loop playsInline className="h-full w-full object-cover"/>:<img src={item.mediaUrl} alt="" className="h-full w-full object-cover"/>}{form.mediaItems.length>1?<><button onClick={()=>setIndex((index-1+form.mediaItems.length)%form.mediaItems.length)} className="absolute left-2 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-black/60 text-white"><ChevronLeft/></button><button onClick={()=>setIndex((index+1)%form.mediaItems.length)} className="absolute right-2 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full bg-black/60 text-white"><ChevronRight/></button><span className="absolute right-3 top-3 rounded-full bg-black/60 px-2 py-1 text-xs font-bold text-white">{index+1}/{form.mediaItems.length}</span></>:null}</div>:<div className="mx-3 grid aspect-[3/4] place-items-center rounded-2xl bg-muted text-sm text-muted-foreground">Selecione uma ou mais mídias</div>}<div className="flex items-center gap-2 p-3">{reactions.length?<div className="flex min-w-0 flex-1 gap-2 overflow-hidden rounded-full border px-3 py-2 text-xs">{reactions.map(([emoji,count])=><span className="shrink-0" key={String(emoji)}>{emoji} {count}</span>)}</div>:<div className="flex-1"/>}<button disabled className="min-h-10 shrink-0 rounded-xl bg-primary px-4 text-sm font-bold text-white">Presentear</button></div></article></div>}
