/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DenunciaRouteImport } from './routes/denuncia'
import { Route as MinhasModelosRouteImport } from './routes/minhas-modelos'
import { Route as PoliticaConteudoRouteImport } from './routes/politica-conteudo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PvRouteImport } from './routes/pv'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as RemocaoRouteImport } from './routes/remocao'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdministradoresRouteImport } from './routes/admin.administradores'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminComprasRouteImport } from './routes/admin.compras'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminConteudosRouteImport } from './routes/admin.conteudos'
import { Route as AdminDemonstracoesRouteImport } from './routes/admin.demonstracoes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminModelosRouteImport } from './routes/admin.modelos'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPromocoesRouteImport } from './routes/admin.promocoes'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as MinhasModelosSlugRouteImport } from './routes/minhas-modelos.$slug'
import { Route as ModeloSlugRouteImport } from './routes/modelo.$slug'
import { Route as AdminConfiguracoesPagamentosRouteImport } from './routes/admin.configuracoes.pagamentos'
import { Route as ApiInternalReconcilePaymentsRouteImport } from './routes/api.internal.reconcile-payments'
import { Route as ApiPublicMediaRouteImport } from './routes/api.public.media'
import { Route as ApiWebhooksSyncpayRouteImport } from './routes/api.webhooks.syncpay'
import { Route as ApiPublicWebhooksProviderRouteImport } from './routes/api/public/webhooks.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciaRoute = DenunciaRouteImport.update({
  id: '/denuncia',
  path: '/denuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasModelosRoute = MinhasModelosRouteImport.update({
  id: '/minhas-modelos',
  path: '/minhas-modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaConteudoRoute = PoliticaConteudoRouteImport.update({
  id: '/politica-conteudo',
  path: '/politica-conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PvRoute = PvRouteImport.update({
  id: '/pv',
  path: '/pv',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const RemocaoRoute = RemocaoRouteImport.update({
  id: '/remocao',
  path: '/remocao',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/admin/administradores',
  path: '/admin/administradores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComprasRoute = AdminComprasRouteImport.update({
  id: '/admin/compras',
  path: '/admin/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosRoute = AdminConteudosRouteImport.update({
  id: '/admin/conteudos',
  path: '/admin/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemonstracoesRoute = AdminDemonstracoesRouteImport.update({
  id: '/admin/demonstracoes',
  path: '/admin/demonstracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelosRoute = AdminModelosRouteImport.update({
  id: '/admin/modelos',
  path: '/admin/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/admin/planos',
  path: '/admin/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/admin/webhooks',
  path: '/admin/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasModelosSlugRoute = MinhasModelosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MinhasModelosRoute,
} as any)
const ModeloSlugRoute = ModeloSlugRouteImport.update({
  id: '/modelo/$slug',
  path: '/modelo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesPagamentosRoute =
  AdminConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const ApiInternalReconcilePaymentsRoute =
  ApiInternalReconcilePaymentsRouteImport.update({
    id: '/api/internal/reconcile-payments',
    path: '/api/internal/reconcile-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSyncpayRoute = ApiWebhooksSyncpayRouteImport.update({
  id: '/api/webhooks/syncpay',
  path: '/api/webhooks/syncpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksProviderRoute =
  ApiPublicWebhooksProviderRouteImport.update({
    id: '/api/public/webhooks/$provider',
    path: '/api/public/webhooks/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/acesso': typeof AcessoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRoute
  '/minhas-modelos': typeof MinhasModelosRouteWithChildren
  '/politica-conteudo': typeof PoliticaConteudoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv': typeof PvRoute
  '/reembolso': typeof ReembolsoRoute
  '/remocao': typeof RemocaoRoute
  '/termos': typeof TermosRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/demonstracoes': typeof AdminDemonstracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/c/$token': typeof CTokenRoute
  '/minhas-modelos/$slug': typeof MinhasModelosSlugRoute
  '/modelo/$slug': typeof ModeloSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/acesso': typeof AcessoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRoute
  '/minhas-modelos': typeof MinhasModelosRouteWithChildren
  '/politica-conteudo': typeof PoliticaConteudoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv': typeof PvRoute
  '/reembolso': typeof ReembolsoRoute
  '/remocao': typeof RemocaoRoute
  '/termos': typeof TermosRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/demonstracoes': typeof AdminDemonstracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/c/$token': typeof CTokenRoute
  '/minhas-modelos/$slug': typeof MinhasModelosSlugRoute
  '/modelo/$slug': typeof ModeloSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/acesso': typeof AcessoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/categorias': typeof CategoriasRoute
  '/contato': typeof ContatoRoute
  '/denuncia': typeof DenunciaRoute
  '/minhas-modelos': typeof MinhasModelosRouteWithChildren
  '/politica-conteudo': typeof PoliticaConteudoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/pv': typeof PvRoute
  '/reembolso': typeof ReembolsoRoute
  '/remocao': typeof RemocaoRoute
  '/termos': typeof TermosRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/demonstracoes': typeof AdminDemonstracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/c/$token': typeof CTokenRoute
  '/minhas-modelos/$slug': typeof MinhasModelosSlugRoute
  '/modelo/$slug': typeof ModeloSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/api/internal/reconcile-payments': typeof ApiInternalReconcilePaymentsRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/webhooks/syncpay': typeof ApiWebhooksSyncpayRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/acesso'
    | '/biblioteca'
    | '/categorias'
    | '/contato'
    | '/denuncia'
    | '/minhas-modelos'
    | '/politica-conteudo'
    | '/privacidade'
    | '/pv'
    | '/reembolso'
    | '/remocao'
    | '/termos'
    | '/admin/administradores'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/conteudos'
    | '/admin/demonstracoes'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/webhooks'
    | '/c/$token'
    | '/minhas-modelos/$slug'
    | '/modelo/$slug'
    | '/admin/'
    | '/admin/configuracoes/pagamentos'
    | '/api/internal/reconcile-payments'
    | '/api/public/media'
    | '/api/webhooks/syncpay'
    | '/api/public/webhooks/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/acesso'
    | '/biblioteca'
    | '/categorias'
    | '/contato'
    | '/denuncia'
    | '/minhas-modelos'
    | '/politica-conteudo'
    | '/privacidade'
    | '/pv'
    | '/reembolso'
    | '/remocao'
    | '/termos'
    | '/admin/administradores'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/conteudos'
    | '/admin/demonstracoes'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/webhooks'
    | '/c/$token'
    | '/minhas-modelos/$slug'
    | '/modelo/$slug'
    | '/admin'
    | '/admin/configuracoes/pagamentos'
    | '/api/internal/reconcile-payments'
    | '/api/public/media'
    | '/api/webhooks/syncpay'
    | '/api/public/webhooks/$provider'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/acesso'
    | '/biblioteca'
    | '/categorias'
    | '/contato'
    | '/denuncia'
    | '/minhas-modelos'
    | '/politica-conteudo'
    | '/privacidade'
    | '/pv'
    | '/reembolso'
    | '/remocao'
    | '/termos'
    | '/admin/administradores'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/conteudos'
    | '/admin/demonstracoes'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/planos'
    | '/admin/promocoes'
    | '/admin/webhooks'
    | '/c/$token'
    | '/minhas-modelos/$slug'
    | '/modelo/$slug'
    | '/admin/'
    | '/admin/configuracoes/pagamentos'
    | '/api/internal/reconcile-payments'
    | '/api/public/media'
    | '/api/webhooks/syncpay'
    | '/api/public/webhooks/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AcessoRoute: typeof AcessoRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CategoriasRoute: typeof CategoriasRoute
  ContatoRoute: typeof ContatoRoute
  DenunciaRoute: typeof DenunciaRoute
  MinhasModelosRoute: typeof MinhasModelosRouteWithChildren
  PoliticaConteudoRoute: typeof PoliticaConteudoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PvRoute: typeof PvRoute
  ReembolsoRoute: typeof ReembolsoRoute
  RemocaoRoute: typeof RemocaoRoute
  TermosRoute: typeof TermosRoute
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminComprasRoute: typeof AdminComprasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRouteWithChildren
  AdminConteudosRoute: typeof AdminConteudosRoute
  AdminDemonstracoesRoute: typeof AdminDemonstracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModelosRoute: typeof AdminModelosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  CTokenRoute: typeof CTokenRoute
  ModeloSlugRoute: typeof ModeloSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiInternalReconcilePaymentsRoute: typeof ApiInternalReconcilePaymentsRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRoute
  ApiWebhooksSyncpayRoute: typeof ApiWebhooksSyncpayRoute
  ApiPublicWebhooksProviderRoute: typeof ApiPublicWebhooksProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncia': {
      id: '/denuncia'
      path: '/denuncia'
      fullPath: '/denuncia'
      preLoaderRoute: typeof DenunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-modelos': {
      id: '/minhas-modelos'
      path: '/minhas-modelos'
      fullPath: '/minhas-modelos'
      preLoaderRoute: typeof MinhasModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-conteudo': {
      id: '/politica-conteudo'
      path: '/politica-conteudo'
      fullPath: '/politica-conteudo'
      preLoaderRoute: typeof PoliticaConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pv': {
      id: '/pv'
      path: '/pv'
      fullPath: '/pv'
      preLoaderRoute: typeof PvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remocao': {
      id: '/remocao'
      path: '/remocao'
      fullPath: '/remocao'
      preLoaderRoute: typeof RemocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/admin/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compras': {
      id: '/admin/compras'
      path: '/admin/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AdminComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos': {
      id: '/admin/conteudos'
      path: '/admin/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AdminConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demonstracoes': {
      id: '/admin/demonstracoes'
      path: '/admin/demonstracoes'
      fullPath: '/admin/demonstracoes'
      preLoaderRoute: typeof AdminDemonstracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modelos': {
      id: '/admin/modelos'
      path: '/admin/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof AdminModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/admin/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-modelos/$slug': {
      id: '/minhas-modelos/$slug'
      path: '/$slug'
      fullPath: '/minhas-modelos/$slug'
      preLoaderRoute: typeof MinhasModelosSlugRouteImport
      parentRoute: typeof MinhasModelosRoute
    }
    '/modelo/$slug': {
      id: '/modelo/$slug'
      path: '/modelo/$slug'
      fullPath: '/modelo/$slug'
      preLoaderRoute: typeof ModeloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/pagamentos': {
      id: '/admin/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/configuracoes/pagamentos'
      preLoaderRoute: typeof AdminConfiguracoesPagamentosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/api/internal/reconcile-payments': {
      id: '/api/internal/reconcile-payments'
      path: '/api/internal/reconcile-payments'
      fullPath: '/api/internal/reconcile-payments'
      preLoaderRoute: typeof ApiInternalReconcilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/syncpay': {
      id: '/api/webhooks/syncpay'
      path: '/api/webhooks/syncpay'
      fullPath: '/api/webhooks/syncpay'
      preLoaderRoute: typeof ApiWebhooksSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$provider': {
      id: '/api/public/webhooks/$provider'
      path: '/api/public/webhooks/$provider'
      fullPath: '/api/public/webhooks/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MinhasModelosRouteChildren {
  MinhasModelosSlugRoute: typeof MinhasModelosSlugRoute
}

const MinhasModelosRouteChildren: MinhasModelosRouteChildren = {
  MinhasModelosSlugRoute: MinhasModelosSlugRoute,
}

const MinhasModelosRouteWithChildren = MinhasModelosRoute._addFileChildren(
  MinhasModelosRouteChildren,
)

interface AdminConfiguracoesRouteChildren {
  AdminConfiguracoesPagamentosRoute: typeof AdminConfiguracoesPagamentosRoute
}

const AdminConfiguracoesRouteChildren: AdminConfiguracoesRouteChildren = {
  AdminConfiguracoesPagamentosRoute: AdminConfiguracoesPagamentosRoute,
}

const AdminConfiguracoesRouteWithChildren =
  AdminConfiguracoesRoute._addFileChildren(AdminConfiguracoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AcessoRoute: AcessoRoute,
  BibliotecaRoute: BibliotecaRoute,
  CategoriasRoute: CategoriasRoute,
  ContatoRoute: ContatoRoute,
  DenunciaRoute: DenunciaRoute,
  MinhasModelosRoute: MinhasModelosRouteWithChildren,
  PoliticaConteudoRoute: PoliticaConteudoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PvRoute: PvRoute,
  ReembolsoRoute: ReembolsoRoute,
  RemocaoRoute: RemocaoRoute,
  TermosRoute: TermosRoute,
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminComprasRoute: AdminComprasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRouteWithChildren,
  AdminConteudosRoute: AdminConteudosRoute,
  AdminDemonstracoesRoute: AdminDemonstracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModelosRoute: AdminModelosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  CTokenRoute: CTokenRoute,
  ModeloSlugRoute: ModeloSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiInternalReconcilePaymentsRoute: ApiInternalReconcilePaymentsRoute,
  ApiPublicMediaRoute: ApiPublicMediaRoute,
  ApiWebhooksSyncpayRoute: ApiWebhooksSyncpayRoute,
  ApiPublicWebhooksProviderRoute: ApiPublicWebhooksProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
