-- Phone is the primary identity for new customer journeys. CPF remains a
-- private technical gateway field so legacy purchases and SyncPay keep working.
create or replace function public.normalize_br_phone(raw_phone text)
returns text
language sql
immutable
as $$
  with cleaned as (select regexp_replace(coalesce(raw_phone, ''), '[^0-9]', '', 'g') as d)
  select case
    when length(d) in (10, 11) then '55' || d
    when length(d) in (12, 13) and d like '55%' then d
    else null
  end from cleaned;
$$;

alter table public.customers add column if not exists normalized_phone text;
update public.customers
set normalized_phone = public.normalize_br_phone(phone)
where normalized_phone is null and public.normalize_br_phone(phone) is not null;
create index if not exists idx_customers_normalized_phone on public.customers(normalized_phone);

alter table public.orders add column if not exists normalized_phone text;
update public.orders
set normalized_phone = public.normalize_br_phone(checkout_phone)
where normalized_phone is null and public.normalize_br_phone(checkout_phone) is not null;
create index if not exists idx_orders_normalized_phone on public.orders(normalized_phone);

-- Preserve access for legacy customers whose telephone was captured only on
-- the checkout/order record. We only fill missing customer phones and never
-- rewrite an existing identity.
update public.customers as customer
set
  phone = legacy_order.normalized_phone,
  normalized_phone = legacy_order.normalized_phone
from (
  select distinct on (customer_id)
    customer_id,
    normalized_phone
  from public.orders
  where customer_id is not null and normalized_phone is not null
  order by customer_id, created_at desc
) as legacy_order
where customer.id = legacy_order.customer_id
  and customer.normalized_phone is null;

create table if not exists public.customer_phone_identities (
  normalized_phone text primary key check (normalized_phone ~ '^55[0-9]{10,11}$'),
  customer_id uuid not null references public.customers(id) on delete cascade,
  created_at timestamptz not null default now()
);
create index if not exists idx_customer_phone_identity_customer
  on public.customer_phone_identities(customer_id);
alter table public.customer_phone_identities enable row level security;
grant all on public.customer_phone_identities to service_role;

insert into public.customer_phone_identities(normalized_phone, customer_id)
select distinct on (normalized_phone) normalized_phone, id
from public.customers
where normalized_phone is not null
order by normalized_phone, created_at asc
on conflict (normalized_phone) do nothing;

create table if not exists public.phone_access_attempts (
  id bigint generated by default as identity primary key,
  phone_hash text not null,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists idx_phone_access_attempts_hash_time
  on public.phone_access_attempts(phone_hash, attempted_at desc);
alter table public.phone_access_attempts enable row level security;
grant all on public.phone_access_attempts to service_role;

create or replace function public.sync_normalized_phone()
returns trigger language plpgsql as $$
begin
  if tg_table_name = 'customers' then
    new.normalized_phone := public.normalize_br_phone(new.phone);
  else
    new.normalized_phone := public.normalize_br_phone(new.checkout_phone);
  end if;
  return new;
end;
$$;
drop trigger if exists trg_customers_normalized_phone on public.customers;
create trigger trg_customers_normalized_phone before insert or update of phone
on public.customers for each row execute function public.sync_normalized_phone();
drop trigger if exists trg_orders_normalized_phone on public.orders;
create trigger trg_orders_normalized_phone before insert or update of checkout_phone
on public.orders for each row execute function public.sync_normalized_phone();
